logging:
  level:
    org.springframework: INFO
    org.springframework.graphql: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.anshuman.graphqldemo.resource.filter.GraphQLFilter: DEBUG
    com.anshuman.graphqldemo.aspect.LoggingAspect: DEBUG
    com.anshuman.graphqldemo: INFO
server:
  port: 8081
spring:
  data:
    rest:
      base-path: rest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dvdrental?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
    username: postgres
    password: postgres
    hikari:
      allow-pool-suspension: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
    websocket:
      path: /graphql
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        cache:
          region:
            factory_class: jcache
          use_query_cache: true
          use_second_level_cache: true
          use_structured_entries: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        generate_statistics: true
        hbm2ddl:
          extra_physical_table_types: PARTITIONED TABLE
        javax:
          cache:
            missing_cache_strategy: create
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            provider_configuration_file_resource_path: ehcache.xml
    show-sql: true
  main:
    lazy-initialization: true
  mvc:
    converters:
      preferred-json-mapper: jackson
  threads:
    virtual:
      enabled: true