logging:
  level:
    org.springframework: INFO
    org.springframework.graphql: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.anshuman.graphqldemo: INFO
    com.anshuman.graphqldemo.util: DEBUG
server:
  port: 8081
spring:
  data:
    rest:
      base-path: rest
    r2dbc:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dvdrental?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
    username: postgres
    password: postgres
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
    websocket:
      path: /graphql
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
    show-sql: true
  main:
    lazy-initialization: true
  mvc:
    converters:
      preferred-json-mapper: jackson
  r2dbc:
    password: anshuman
    username: anshuman
    url: r2dbc:postgresql://localhost:5432/dvdrental?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
    name: dvdrental
    pool:
      enabled: true